name: Deploy Prod

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: function-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_PROD }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Functions (Prod)
        uses: Azure/functions-action@v1
        with:
          app-name: 'func-devnews-api-prod'
          package: './publish'
